import { Component } from '@angular/core';
import { ReplaySubject, throwError, of, EMPTY } from 'rxjs';
import { retry, catchError } from 'rxjs/operators';

import { ExerciseService } from '../exercise.service';

@Component({
  selector: 'rxw-error-handling',
  templateUrl: './error-handling.component.html',
})
export class ErrorHandlingComponent {

  logStream$ = new ReplaySubject();

  constructor(private es: ExerciseService) { }

  start() {
    this.es.randomError().pipe(
      // retry(4),
      catchError(err => {
        console.log('MEIN FEHLER:', err);

        // return throwError('BÃ¶ser Fehler.'); // weiterwerfen
        // return of('Hier war kein Fehler!'); // ersetzen
        return EMPTY; // verschlucken
      })
    ).subscribe({
      next: value => this.logStream$.next(value),
      error: err => this.logStream$.next('ðŸ’¥ ERROR: ' + err)
    });
  }
}
